package view;

import listener.CadastroClienteListener;
import validacoes.ImpedirCaracteres;

public class CadastrarClienteJIF extends javax.swing.JInternalFrame {

    private CadastroClienteListener eventCF = new CadastroClienteListener(this);

    public CadastrarClienteJIF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        camponomerazao = new javax.swing.JTextField();
        campocpfcnpj = new javax.swing.JTextField();
        salvarcliente = new javax.swing.JButton();
        cancelarcliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campotelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoemail = new javax.swing.JTextField();
        consultarcliente = new javax.swing.JButton();
        pessoaFisica = new javax.swing.JRadioButton();
        pessoaJuridica = new javax.swing.JRadioButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Cadastrar Cliente");

        jLabel1.setText("Nome/Razão Social:");

        jLabel2.setText("CPF/CNPJ:");

        camponomerazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponomerazaoActionPerformed(evt);
            }
        });
        camponomerazao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                camponomerazaoKeyTyped(evt);
            }
        });

        campocpfcnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campocpfcnpjKeyTyped(evt);
            }
        });

        salvarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Checked-16.png"))); // NOI18N
        salvarcliente.setText("Salvar");
        salvarcliente.addActionListener(eventCF);
        salvarcliente.setActionCommand("salvar");

        cancelarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel-16.png"))); // NOI18N
        cancelarcliente.setText("Cancelar");
        cancelarcliente.addActionListener(eventCF);
        cancelarcliente.setActionCommand("cancelar");

        jLabel3.setText("Telefone:");

        campotelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campotelefoneKeyTyped(evt);
            }
        });

        jLabel4.setText("Email:");

        campoemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoemailKeyTyped(evt);
            }
        });

        consultarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search-16.png"))); // NOI18N
        consultarcliente.setText("Consultar");
        consultarcliente.addActionListener(eventCF);
        consultarcliente.setActionCommand("consultar");

        pessoaFisica.setText("Pessoa Física");
        pessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaFisicaActionPerformed(evt);
            }
        });

        pessoaJuridica.setText("Pessoa Jurídica");
        pessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pessoaFisica)
                        .addGap(9, 9, 9)
                        .addComponent(pessoaJuridica))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campotelefone)
                                .addComponent(campocpfcnpj)
                                .addComponent(campoemail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(camponomerazao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(salvarcliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(consultarcliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelarcliente))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(camponomerazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(campocpfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campotelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pessoaFisica)
                    .addComponent(pessoaJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarcliente)
                    .addComponent(salvarcliente)
                    .addComponent(cancelarcliente))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camponomerazaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camponomerazaoKeyTyped
        ImpedirCaracteres.bloquearCaracteres(false, true, null, evt);
    }//GEN-LAST:event_camponomerazaoKeyTyped

    private void campotelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campotelefoneKeyTyped
        ImpedirCaracteres.bloquearCaracteres(true, false, null, evt);
    }//GEN-LAST:event_campotelefoneKeyTyped

    private void campocpfcnpjKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campocpfcnpjKeyTyped
        ImpedirCaracteres.bloquearCaracteres(true, false, null, evt);
    }//GEN-LAST:event_campocpfcnpjKeyTyped

    private void campoemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoemailKeyTyped
        ImpedirCaracteres.bloquearCaracteres(true, true, ".@", evt);
    }//GEN-LAST:event_campoemailKeyTyped

    private void camponomerazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponomerazaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponomerazaoActionPerformed

    private void pessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaJuridicaActionPerformed
        pessoaFisica.setSelected(false);
    }//GEN-LAST:event_pessoaJuridicaActionPerformed

    private void pessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaFisicaActionPerformed
        pessoaJuridica.setSelected(false);
    }//GEN-LAST:event_pessoaFisicaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField campocpfcnpj;
    public javax.swing.JTextField campoemail;
    public javax.swing.JTextField camponomerazao;
    public javax.swing.JTextField campotelefone;
    private javax.swing.JButton cancelarcliente;
    private javax.swing.JButton consultarcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JRadioButton pessoaFisica;
    public javax.swing.JRadioButton pessoaJuridica;
    private javax.swing.JButton salvarcliente;
    // End of variables declaration//GEN-END:variables
}
