package view;

import listener.ConsultaClienteListener;
import validacoes.ImpedirCaracteres;

public class ConsultarClienteJIF extends javax.swing.JInternalFrame {

    private ConsultaClienteListener eventC = new ConsultaClienteListener(this);

    public ConsultarClienteJIF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        camponomerazao = new javax.swing.JTextField();
        campocpfcnpj = new javax.swing.JTextField();
        salvarclientealteracao = new javax.swing.JButton();
        cancelarclientealteracao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campotelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoemail = new javax.swing.JTextField();
        pessoaFisicaalteracao = new javax.swing.JRadioButton();
        pessoaJuridicaalteracao = new javax.swing.JRadioButton();
        excluircliente = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Cliente");

        jLabel1.setText("Nome/Razão Social:");

        jLabel2.setText("CPF/CNPJ:");

        camponomerazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponomerazaoActionPerformed(evt);
            }
        });
        camponomerazao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                camponomerazaoKeyTyped(evt);
            }
        });

        campocpfcnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campocpfcnpjKeyTyped(evt);
            }
        });

        salvarclientealteracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Checked-16.png"))); // NOI18N
        salvarclientealteracao.setText("Salvar");
        salvarclientealteracao.addActionListener(eventC);
        salvarclientealteracao.setActionCommand("salvar");

        cancelarclientealteracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel-16.png"))); // NOI18N
        cancelarclientealteracao.setText("Fechar");
        cancelarclientealteracao.addActionListener(eventC);
        cancelarclientealteracao.setActionCommand("cancelar");

        jLabel3.setText("Telefone:");

        campotelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campotelefoneKeyTyped(evt);
            }
        });

        jLabel4.setText("Email:");

        campoemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoemailKeyTyped(evt);
            }
        });

        pessoaFisicaalteracao.setText("Pessoa Física");
        pessoaFisicaalteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaFisicaalteracaoActionPerformed(evt);
            }
        });

        pessoaJuridicaalteracao.setText("Pessoa Jurídica");
        pessoaJuridicaalteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaJuridicaalteracaoActionPerformed(evt);
            }
        });

        excluircliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete-16.png"))); // NOI18N
        excluircliente.setText("Excluir");
        excluircliente.addActionListener(eventC);
        excluircliente.setActionCommand("excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarclientealteracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluircliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarclientealteracao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pessoaFisicaalteracao)
                        .addGap(9, 9, 9)
                        .addComponent(pessoaJuridicaalteracao))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campotelefone)
                                .addComponent(campocpfcnpj)
                                .addComponent(campoemail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(camponomerazao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(camponomerazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(campocpfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campotelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pessoaFisicaalteracao)
                    .addComponent(pessoaJuridicaalteracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarclientealteracao)
                    .addComponent(cancelarclientealteracao)
                    .addComponent(excluircliente))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camponomerazaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camponomerazaoKeyTyped
        ImpedirCaracteres.bloquearCaracteres(false, true, null, evt);
    }//GEN-LAST:event_camponomerazaoKeyTyped

    private void campotelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campotelefoneKeyTyped
        ImpedirCaracteres.bloquearCaracteres(true, false, null, evt);
    }//GEN-LAST:event_campotelefoneKeyTyped

    private void campocpfcnpjKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campocpfcnpjKeyTyped
        ImpedirCaracteres.bloquearCaracteres(true, false, null, evt);
    }//GEN-LAST:event_campocpfcnpjKeyTyped

    private void campoemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoemailKeyTyped
        ImpedirCaracteres.bloquearCaracteres(true, true, ".@", evt);
    }//GEN-LAST:event_campoemailKeyTyped

    private void camponomerazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponomerazaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponomerazaoActionPerformed

    private void pessoaJuridicaalteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaJuridicaalteracaoActionPerformed
        pessoaFisicaalteracao.setSelected(false);
    }//GEN-LAST:event_pessoaJuridicaalteracaoActionPerformed

    private void pessoaFisicaalteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaFisicaalteracaoActionPerformed
        pessoaJuridicaalteracao.setSelected(false);
    }//GEN-LAST:event_pessoaFisicaalteracaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField campocpfcnpj;
    public javax.swing.JTextField campoemail;
    public javax.swing.JTextField camponomerazao;
    public javax.swing.JTextField campotelefone;
    private javax.swing.JButton cancelarclientealteracao;
    private javax.swing.JButton excluircliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JRadioButton pessoaFisicaalteracao;
    public javax.swing.JRadioButton pessoaJuridicaalteracao;
    private javax.swing.JButton salvarclientealteracao;
    // End of variables declaration//GEN-END:variables
}
