


import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class ExcluirClienteJuridico extends javax.swing.JInternalFrame {

    private ExcluirJuridicoListener eventEJ = new ExcluirJuridicoListener(this);
    public ExcluirClienteJuridico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cnpjexcluir = new javax.swing.JTextField();
        excluirjuridico = new javax.swing.JButton();
        cancelarjuridico = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Excluir Cliente Jurídico");

        jLabel1.setText("Insira o CNPJ a ser excluido:");

        cnpjexcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnpjexcluirKeyTyped(evt);
            }
        });

        excluirjuridico.setText("Excluir");
        excluirjuridico.addActionListener(eventEJ);
        excluirjuridico.setActionCommand("excluir");
        excluirjuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjuridicoActionPerformed(evt);
            }
        });

        cancelarjuridico.setText("Cancelar");
        cancelarjuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjuridicoActionPerformed(evt);
            }
        });
        cancelarjuridico.addActionListener(eventEJ);
        cancelarjuridico.setActionCommand("cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cnpjexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(excluirjuridico)
                        .addGap(80, 80, 80)
                        .addComponent(cancelarjuridico)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cnpjexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirjuridico)
                    .addComponent(cancelarjuridico))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarjuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarjuridicoActionPerformed

    private void excluirjuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjuridicoActionPerformed
        try {
            SalvaLogs.escrever("Excluir Cliente Jurídico", "C:\\Users\\comp1\\Desktop\\logs.txt", true);
        } catch (IOException ex) {
            System.out.println("Erro");
        }
    }//GEN-LAST:event_excluirjuridicoActionPerformed

    private void cnpjexcluirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnpjexcluirKeyTyped
        String caracteres = "0987654321";// lista de caracters que devem ser aceitos
        if (!caracteres.contains(evt.getKeyChar() + "")) {// se o caracter que gerou o evento estiver não estiver na lista
            evt.consume();//aciona esse propriedade para eliminar a ação do evento
        }
    }//GEN-LAST:event_cnpjexcluirKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjuridico;
    private javax.swing.JTextField cnpjexcluir;
    private javax.swing.JButton excluirjuridico;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
