


import java.io.IOException;


public class ExcluirClienteFisico extends javax.swing.JInternalFrame {

    private ExcluirFisicoListener eventEF = new ExcluirFisicoListener(this);
    public ExcluirClienteFisico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cpfexcluir = new javax.swing.JTextField();
        excluirfisico = new javax.swing.JButton();
        cancelarexcluirfisico = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Excluir Cliente Físico");

        jLabel1.setText("Insira o CPF a ser excluido:");

        cpfexcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpfexcluirKeyTyped(evt);
            }
        });

        excluirfisico.setText("Excluir");
        excluirfisico.addActionListener(eventEF);
        excluirfisico.setActionCommand("excluir");
        excluirfisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirfisicoActionPerformed(evt);
            }
        });

        cancelarexcluirfisico.setText("Cancelar");
        cancelarexcluirfisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarexcluirfisicoActionPerformed(evt);
            }
        });
        cancelarexcluirfisico.addActionListener(eventEF);
        cancelarexcluirfisico.setActionCommand("cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(excluirfisico)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(cancelarexcluirfisico)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cpfexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirfisico)
                    .addComponent(cancelarexcluirfisico))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarexcluirfisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarexcluirfisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarexcluirfisicoActionPerformed

    private void excluirfisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirfisicoActionPerformed
        try {
            SalvaLogs.escrever("Excluir Cliente Físico", "C:\\Users\\comp1\\Desktop\\logs.txt", true);
        } catch (IOException ex) {
            System.out.println("Erro");
        }
    }//GEN-LAST:event_excluirfisicoActionPerformed

    private void cpfexcluirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfexcluirKeyTyped
        String caracteres = "0987654321";// lista de caracters que devem ser aceitos
        if (!caracteres.contains(evt.getKeyChar() + "")) {// se o caracter que gerou o evento estiver não estiver na lista
            evt.consume();//aciona esse propriedade para eliminar a ação do evento
        }
    }//GEN-LAST:event_cpfexcluirKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarexcluirfisico;
    private javax.swing.JTextField cpfexcluir;
    private javax.swing.JButton excluirfisico;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
